services:
  telemt-panel:
    build: .
    volumes:
      - ./config.toml:/etc/telemt-panel/config.toml
      - telemt-panel-data:/var/lib/telemt-panel
    restart: unless-stopped
    network_mode: host

volumes:
  telemt-panel-data:
