// scripts/generate-icons.mjs — renders public/icon.svg to PNG at the sizes
// the web app manifest / apple-touch-icon need (Task 9 deliverable D: the
// "SVG-only manifest icons (iOS gap)" carried from Task 4's report —
// Safari's "add to home screen" ignores `rel="icon"`/manifest SVG entries
// entirely and needs a real `rel="apple-touch-icon"` PNG).
//
// No new dependency: @playwright/test (installed for Task 9's e2e suite,
// web/package.json) already bundles a Chromium build, so this script
// screenshots the SVG rendered in a real browser instead of pulling in a
// raster/SVG-to-PNG library (sharp, resvg, etc — all unapproved new
// dependencies). One-off/dev-time only — run manually whenever
// public/icon.svg changes; the PNGs it writes are committed like any other
// static asset, not regenerated by `npm run build`.
//
// The brand mark is a gradient, and a 512px smooth gradient is exactly what
// PNG's filters compress worst — Chromium's 24-bit output was 121 kB for
// icon-512 alone. The committed PNGs are therefore palette-quantized to 256
// colors after this script runs (6.5 kB, no visible banding at icon sizes);
// no library is added for it, since the step is manual and dev-time only:
//
//   python3 - <<'EOF'
//   from PIL import Image
//   for f in ["icon-192.png", "icon-512.png", "apple-touch-icon.png"]:
//       im = Image.open(f)
//       alpha = im.mode in ("RGBA", "LA") and im.getchannel("A").getextrema()[0] < 255
//       src = im.convert("RGBA") if alpha else im.convert("RGB")
//       m = Image.Quantize.FASTOCTREE if alpha else Image.Quantize.MEDIANCUT
//       src.quantize(colors=256, method=m).save(f, optimize=True)
//   EOF
//
// Usage: node scripts/generate-icons.mjs
import { chromium } from "@playwright/test";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = path.join(__dirname, "..", "public");
const svgMarkup = readFileSync(path.join(PUBLIC_DIR, "icon.svg"), "utf8");

// { file, size, opaque }: `opaque` paints the page background too, needed
// for apple-touch-icon — iOS composites it directly with no transparency
// handling, so a transparent PNG there would show as black.
const TARGETS = [
  { file: "icon-192.png", size: 192, opaque: false },
  { file: "icon-512.png", size: 512, opaque: false },
  { file: "apple-touch-icon.png", size: 180, opaque: true },
];

async function main() {
  const browser = await chromium.launch();
  try {
    for (const { file, size, opaque } of TARGETS) {
      const page = await browser.newPage({
        viewport: { width: size, height: size },
        deviceScaleFactor: 1,
      });
      const html = `<!doctype html><html><head><style>
        html,body{margin:0;padding:0;width:${size}px;height:${size}px;${opaque ? "background:#0b0d10;" : ""}}
        svg{display:block;width:${size}px;height:${size}px;}
      </style></head><body>${svgMarkup}</body></html>`;
      await page.setContent(html);
      const bytes = await page.screenshot({ omitBackground: !opaque });
      writeFileSync(path.join(PUBLIC_DIR, file), bytes);
      await page.close();
      console.log(`wrote public/${file} (${size}x${size}${opaque ? ", opaque" : ""})`);
    }
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
