// scripts/generate-icons.mjs — renders public/icon.svg to PNG at the sizes
// the web app manifest / apple-touch-icon need (Task 9 deliverable D: the
// "SVG-only manifest icons (iOS gap)" carried from Task 4's report —
// Safari's "add to home screen" ignores `rel="icon"`/manifest SVG entries
// entirely and needs a real `rel="apple-touch-icon"` PNG).
//
// No new dependency: @playwright/test (installed for Task 9's e2e suite,
// web/package.json) already bundles a Chromium build, so this script
// screenshots the SVG rendered in a real browser instead of pulling in a
// raster/SVG-to-PNG library (sharp, resvg, etc — all unapproved new
// dependencies). One-off/dev-time only — run manually whenever
// public/icon.svg changes; the PNGs it writes are committed like any other
// static asset, not regenerated by `npm run build`.
//
// Usage: node scripts/generate-icons.mjs
import { chromium } from "@playwright/test";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = path.join(__dirname, "..", "public");
const svgMarkup = readFileSync(path.join(PUBLIC_DIR, "icon.svg"), "utf8");

// { file, size, opaque }: `opaque` paints the page background too, needed
// for apple-touch-icon — iOS composites it directly with no transparency
// handling, so a transparent PNG there would show as black.
const TARGETS = [
  { file: "icon-192.png", size: 192, opaque: false },
  { file: "icon-512.png", size: 512, opaque: false },
  { file: "apple-touch-icon.png", size: 180, opaque: true },
];

async function main() {
  const browser = await chromium.launch();
  try {
    for (const { file, size, opaque } of TARGETS) {
      const page = await browser.newPage({
        viewport: { width: size, height: size },
        deviceScaleFactor: 1,
      });
      const html = `<!doctype html><html><head><style>
        html,body{margin:0;padding:0;width:${size}px;height:${size}px;${opaque ? "background:#0b0d10;" : ""}}
        svg{display:block;width:${size}px;height:${size}px;}
      </style></head><body>${svgMarkup}</body></html>`;
      await page.setContent(html);
      const bytes = await page.screenshot({ omitBackground: !opaque });
      writeFileSync(path.join(PUBLIC_DIR, file), bytes);
      await page.close();
      console.log(`wrote public/${file} (${size}x${size}${opaque ? ", opaque" : ""})`);
    }
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
