/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedJournalRouteImport } from './routes/_authed/journal'
import { Route as AuthedPeopleRouteRouteImport } from './routes/_authed/people/route'
import { Route as AuthedPulseRouteImport } from './routes/_authed/pulse'
import { Route as AuthedServerRouteImport } from './routes/_authed/server'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as AuthedPeopleIndexRouteImport } from './routes/_authed/people/index'
import { Route as AuthedPeopleUsernameRouteImport } from './routes/_authed/people/$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedJournalRoute = AuthedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleRouteRoute = AuthedPeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPulseRoute = AuthedPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServerRoute = AuthedServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthedRoute,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPeopleIndexRoute = AuthedPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPeopleRouteRoute,
} as any)
const AuthedPeopleUsernameRoute = AuthedPeopleUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AuthedPeopleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/people': typeof AuthedPeopleRouteRouteWithChildren
  '/journal': typeof AuthedJournalRoute
  '/pulse': typeof AuthedPulseRoute
  '/server': typeof AuthedServerRoute
  '/dev/ui': typeof DevUiRoute
  '/people/$username': typeof AuthedPeopleUsernameRoute
  '/people/': typeof AuthedPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/journal': typeof AuthedJournalRoute
  '/pulse': typeof AuthedPulseRoute
  '/server': typeof AuthedServerRoute
  '/dev/ui': typeof DevUiRoute
  '/people/$username': typeof AuthedPeopleUsernameRoute
  '/people': typeof AuthedPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/people': typeof AuthedPeopleRouteRouteWithChildren
  '/_authed/journal': typeof AuthedJournalRoute
  '/_authed/pulse': typeof AuthedPulseRoute
  '/_authed/server': typeof AuthedServerRoute
  '/dev/ui': typeof DevUiRoute
  '/_authed/people/$username': typeof AuthedPeopleUsernameRoute
  '/_authed/people/': typeof AuthedPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/people'
    | '/journal'
    | '/pulse'
    | '/server'
    | '/dev/ui'
    | '/people/$username'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/journal'
    | '/pulse'
    | '/server'
    | '/dev/ui'
    | '/people/$username'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/people'
    | '/_authed/journal'
    | '/_authed/pulse'
    | '/_authed/server'
    | '/dev/ui'
    | '/_authed/people/$username'
    | '/_authed/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  DevUiRoute: typeof DevUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/journal': {
      id: '/_authed/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthedJournalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people': {
      id: '/_authed/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthedPeopleRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pulse': {
      id: '/_authed/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof AuthedPulseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/server': {
      id: '/_authed/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthedServerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/people/': {
      id: '/_authed/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthedPeopleIndexRouteImport
      parentRoute: typeof AuthedPeopleRouteRoute
    }
    '/_authed/people/$username': {
      id: '/_authed/people/$username'
      path: '/$username'
      fullPath: '/people/$username'
      preLoaderRoute: typeof AuthedPeopleUsernameRouteImport
      parentRoute: typeof AuthedPeopleRouteRoute
    }
  }
}

interface AuthedPeopleRouteRouteChildren {
  AuthedPeopleUsernameRoute: typeof AuthedPeopleUsernameRoute
  AuthedPeopleIndexRoute: typeof AuthedPeopleIndexRoute
}

const AuthedPeopleRouteRouteChildren: AuthedPeopleRouteRouteChildren = {
  AuthedPeopleUsernameRoute: AuthedPeopleUsernameRoute,
  AuthedPeopleIndexRoute: AuthedPeopleIndexRoute,
}

const AuthedPeopleRouteRouteWithChildren =
  AuthedPeopleRouteRoute._addFileChildren(AuthedPeopleRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedPeopleRouteRoute: typeof AuthedPeopleRouteRouteWithChildren
  AuthedJournalRoute: typeof AuthedJournalRoute
  AuthedPulseRoute: typeof AuthedPulseRoute
  AuthedServerRoute: typeof AuthedServerRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPeopleRouteRoute: AuthedPeopleRouteRouteWithChildren,
  AuthedJournalRoute: AuthedJournalRoute,
  AuthedPulseRoute: AuthedPulseRoute,
  AuthedServerRoute: AuthedServerRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  DevUiRoute: DevUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
