// Deterministic pseudo-randomness for the production-size fixtures.
//
// Every fixture in this directory is built at module load from one of these
// generators, never from Math.random or Date.now: the details-builder's
// completeness and layout tests compare whole rendered trees, so a fixture
// that changed between runs would make a failure impossible to reproduce.
// A seed is a plain number, so any fixture can be regenerated byte-identical
// by re-running the same module.

// mulberry32 — a 32-bit PRNG with a well-distributed output for the small
// draw counts these fixtures need. Chosen for being four lines of arithmetic
// with no dependency, not for cryptographic quality: these are display
// fixtures, and repeatability is the only property that matters.
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Rng bundles the draws the fixtures actually need. Every method is
// inclusive of both bounds where a range is given, matching how the ranges
// are written in TELEMT_LIVE_API_DATA.md (§8's "0–31", §9's "4–342 ms").
export interface Rng {
  /** Float in [0, 1). */
  next(): number;
  /** Integer in [min, max], both inclusive. */
  int(min: number, max: number): number;
  /** True with probability p. */
  chance(p: number): boolean;
  /** One element of a non-empty list. */
  pick<T>(items: readonly T[]): T;
  /** Fixed-precision float in [min, max]. */
  float(min: number, max: number, decimals?: number): number;
}

export function rng(seed: number): Rng {
  const next = mulberry32(seed);
  const int = (min: number, max: number) => min + Math.floor(next() * (max - min + 1));
  return {
    next,
    int,
    chance: (p) => next() < p,
    pick: (items) => items[int(0, items.length - 1)],
    float: (min, max, decimals = 1) => {
      const factor = 10 ** decimals;
      return Math.round((min + next() * (max - min)) * factor) / factor;
    },
  };
}

// spread returns `count` values walked evenly across [min, max] — used
// where a fixture must provably touch both ends of a documented range
// (endpoints per DC 1–10, writer RTT 4–473) instead of leaving the extremes
// to chance. The first value is always min and the last always max.
export function spread(count: number, min: number, max: number): number[] {
  if (count <= 1) return [min];
  const step = (max - min) / (count - 1);
  return Array.from({ length: count }, (_, i) => Math.round(min + step * i));
}

// times builds an array of `count` items from an index-taking factory —
// the shape every collection fixture below uses.
export function times<T>(count: number, make: (index: number) => T): T[] {
  return Array.from({ length: count }, (_, i) => make(i));
}
